# Generated by Django 2.1.4 on 2019-07-20 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20190720_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeimageblock',
            name='id',
        ),
        migrations.RemoveField(
            model_name='recipetextblock',
            name='id',
        ),
        migrations.RemoveField(
            model_name='recipetimerblock',
            name='id',
        ),
        migrations.AddField(
            model_name='recipeimageblock',
            name='recipeblock_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recipes.RecipeBlock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipetextblock',
            name='recipeblock_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recipes.RecipeBlock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipetimerblock',
            name='recipeblock_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recipes.RecipeBlock'),
            preserve_default=False,
        ),
    ]
