# Generated by Django 2.1.4 on 2019-07-20 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('recipes', '0006_auto_20190720_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeblock',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='recipeimageblock',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='recipetextblock',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='recipetimerblock',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='recipeblock',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_recipes.recipeblock_set+', to='contenttypes.ContentType'),
        ),
    ]
