# Generated by Django 2.1.4 on 2019-07-20 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20190720_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeblock',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='recipes.RecipeStep'),
        ),
    ]
